#!/usr/bin/env bash
# @GenAI-START - Generated by Cursor on 2026-09-13
#
# Walks through both use cases against a running service.
# Start the service first (mvn spring-boot:run), then run: ./demo.sh
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:8080}"
FIXED_JACKPOT="jackpot-fixed-1"
VARIABLE_JACKPOT="jackpot-variable-1"
RUN_ID="demo-$(date +%s)"

say() { printf '\n\033[1;36m%s\033[0m\n' "$*"; }

pretty() {
  if command -v jq > /dev/null 2>&1; then jq .; else cat; echo; fi
}

get() { curl -sS "$BASE_URL$1" | pretty; }

publish_bet() {
  curl -sS -X POST "$BASE_URL/api/v1/bets" \
    -H 'Content-Type: application/json' \
    -d "{\"betId\":\"$1\",\"userId\":\"$2\",\"jackpotId\":\"$3\",\"betAmount\":$4}" | pretty
}

evaluate_bet() { curl -sS -X POST "$BASE_URL/api/v1/bets/$1/evaluate" | pretty; }

if ! curl -sS -o /dev/null "$BASE_URL/api/v1/jackpots"; then
  echo "The service is not reachable at $BASE_URL. Start it with: mvn spring-boot:run" >&2
  exit 1
fi

say "1. The configured jackpots, with the contribution rate and win chance that apply right now"
get /api/v1/jackpots

say "2. Publish a 200.00 bet to the fixed jackpot (contributes a flat 5% = 10.00)"
publish_bet "$RUN_ID-fixed" "user-42" "$FIXED_JACKPOT" "200.00"

say "3. The fixed jackpot pool has grown by exactly 10.00"
get "/api/v1/jackpots/$FIXED_JACKPOT"

say "4. The stored contribution record for that bet"
get "/api/v1/jackpots/$FIXED_JACKPOT/contributions"

say "5. Publish two 1000.00 bets to the variable jackpot and watch the rate decay"
publish_bet "$RUN_ID-var-1" "user-42" "$VARIABLE_JACKPOT" "1000.00"
publish_bet "$RUN_ID-var-2" "user-42" "$VARIABLE_JACKPOT" "1000.00"

say "6. The second bet contributed slightly less than the first, because the pool grew"
get "/api/v1/jackpots/$VARIABLE_JACKPOT/contributions"

say "7. A large bet pushes the variable pool to its limit, making the win chance 100%"
publish_bet "$RUN_ID-var-big" "user-42" "$VARIABLE_JACKPOT" "500000.00"
get "/api/v1/jackpots/$VARIABLE_JACKPOT"

say "8. Evaluate that bet: a pool at its limit always wins"
evaluate_bet "$RUN_ID-var-big"

say "9. The pool has been reset to its initial value and the chance is back to its floor"
get "/api/v1/jackpots/$VARIABLE_JACKPOT"

say "10. Re-evaluating replays the stored outcome instead of paying out again"
evaluate_bet "$RUN_ID-var-big"

say "11. Evaluate the fixed-jackpot bet, which has a 10% chance of winning"
evaluate_bet "$RUN_ID-fixed"

say "Done. Check the service log for the [MOCK KAFKA] payload lines."
# @GenAI-END
