// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service;

import com.sportsgroup.jackpot.domain.Bet;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.JackpotContribution;
import com.sportsgroup.jackpot.messaging.BetMessage;
import com.sportsgroup.jackpot.repository.BetRepository;
import com.sportsgroup.jackpot.repository.JackpotContributionRepository;
import com.sportsgroup.jackpot.repository.JackpotRepository;
import com.sportsgroup.jackpot.service.contribution.ContributionCalculator;
import com.sportsgroup.jackpot.service.contribution.ContributionCalculators;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Clock;
import java.util.Optional;

/**
 * Use cases 2 and 3: the consumer side. Every consumed bet contributes to its matching
 * jackpot pool according to that jackpot's own configuration.
 *
 * <p>The whole unit of work is one transaction: the pool increase and the contribution
 * record either both happen or neither does.
 */
@Service
public class BetProcessingService {

    private static final Logger log = LoggerFactory.getLogger(BetProcessingService.class);

    private final BetRepository betRepository;
    private final JackpotRepository jackpotRepository;
    private final JackpotContributionRepository contributionRepository;
    private final ContributionCalculators contributionCalculators;
    private final Clock clock;

    public BetProcessingService(BetRepository betRepository,
                                JackpotRepository jackpotRepository,
                                JackpotContributionRepository contributionRepository,
                                ContributionCalculators contributionCalculators,
                                Clock clock) {
        this.betRepository = betRepository;
        this.jackpotRepository = jackpotRepository;
        this.contributionRepository = contributionRepository;
        this.contributionCalculators = contributionCalculators;
        this.clock = clock;
    }

    /**
     * Contributes a consumed bet to its jackpot.
     *
     * @return the stored contribution, or empty when the bet was a redelivery or no
     *         jackpot matched the bet's jackpot id
     */
    @Transactional
    public Optional<JackpotContribution> process(BetMessage betMessage) {
        String betId = betMessage.betId();

        // At-least-once delivery means the same bet can arrive twice; the unique bet id on
        // the contribution table is the backstop, this check keeps the happy path quiet.
        if (contributionRepository.existsByBetId(betId)) {
            log.info("Bet {} has already contributed, ignoring redelivery", betId);
            return Optional.empty();
        }

        Bet bet = betRepository.findById(betId)
                .orElseGet(() -> betRepository.save(new Bet(
                        betId,
                        betMessage.userId(),
                        betMessage.jackpotId(),
                        betMessage.betAmount(),
                        clock.instant())));

        Optional<Jackpot> matchingJackpot = jackpotRepository.findByIdForUpdate(betMessage.jackpotId());
        if (matchingJackpot.isEmpty()) {
            bet.markNoMatchingJackpot();
            log.warn("Bet {} references unknown jackpot {}, nothing contributed",
                    betId, betMessage.jackpotId());
            return Optional.empty();
        }

        Jackpot jackpot = matchingJackpot.get();
        ContributionCalculator calculator =
                contributionCalculators.forType(jackpot.getContributionConfig().getType());

        BigDecimal contributionPercentage = calculator.contributionPercentage(jackpot);
        BigDecimal contributionAmount = calculator.contributionAmount(jackpot, betMessage.betAmount());
        BigDecimal poolAmountAfterContribution = jackpot.contribute(contributionAmount);

        JackpotContribution contribution = contributionRepository.save(new JackpotContribution(
                betId,
                betMessage.userId(),
                jackpot.getId(),
                betMessage.betAmount(),
                contributionAmount,
                poolAmountAfterContribution,
                clock.instant()));

        bet.markContributed();

        log.info("Bet {} contributed {} ({}% of {}) to jackpot {}, pool is now {}",
                betId, contributionAmount, contributionPercentage, betMessage.betAmount(),
                jackpot.getId(), poolAmountAfterContribution);

        return Optional.of(contribution);
    }
}
// @GenAI-END
