// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service;

import com.sportsgroup.jackpot.domain.Bet;
import com.sportsgroup.jackpot.exception.DuplicateBetException;
import com.sportsgroup.jackpot.messaging.BetMessage;
import com.sportsgroup.jackpot.repository.BetRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;

/**
 * Persists accepted bets in their own transaction.
 *
 * <p>Separated from {@link BetService} so that the bet row is committed before the message
 * is published. Without that, a consumer running in another transaction could look for a
 * bet that is not visible yet.
 */
@Component
public class BetRecorder {

    private final BetRepository betRepository;
    private final Clock clock;

    public BetRecorder(BetRepository betRepository, Clock clock) {
        this.betRepository = betRepository;
        this.clock = clock;
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public Bet record(BetMessage betMessage) {
        if (betRepository.existsById(betMessage.betId())) {
            throw new DuplicateBetException(betMessage.betId());
        }
        Bet bet = new Bet(
                betMessage.betId(),
                betMessage.userId(),
                betMessage.jackpotId(),
                betMessage.betAmount(),
                clock.instant());
        return betRepository.save(bet);
    }

    /**
     * Undoes {@link #record} when the bet could not be published, so the client can retry
     * with the same bet id instead of being permanently rejected as a duplicate.
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void discard(String betId) {
        betRepository.deleteById(betId);
    }
}
// @GenAI-END
