// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service;

import com.sportsgroup.jackpot.domain.Bet;
import com.sportsgroup.jackpot.messaging.BetMessage;
import com.sportsgroup.jackpot.messaging.BetPublisher;
import com.sportsgroup.jackpot.repository.BetRepository;
import com.sportsgroup.jackpot.exception.BetNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Use case 1: accept a bet and publish it to the {@code jackpot-bets} topic.
 *
 * <p>Deliberately not transactional: the bet is recorded in its own committed transaction
 * and only then published, because a message must never be published from inside a
 * transaction that might still roll back.
 */
@Service
public class BetService {

    private static final Logger log = LoggerFactory.getLogger(BetService.class);

    private final BetRecorder betRecorder;
    private final BetPublisher betPublisher;
    private final BetRepository betRepository;

    public BetService(BetRecorder betRecorder,
                      BetPublisher betPublisher,
                      BetRepository betRepository) {
        this.betRecorder = betRecorder;
        this.betPublisher = betPublisher;
        this.betRepository = betRepository;
    }

    /**
     * Records the bet, publishes it, and returns the stored bet.
     *
     * @throws com.sportsgroup.jackpot.exception.DuplicateBetException  if the bet id was already accepted
     * @throws com.sportsgroup.jackpot.exception.BetPublishFailedException if the message could not be published
     */
    public Bet publishBet(BetMessage betMessage) {
        betRecorder.record(betMessage);
        try {
            betPublisher.publish(betMessage);
        } catch (RuntimeException e) {
            log.error("Rolling back bet {} because it could not be published", betMessage.betId());
            betRecorder.discard(betMessage.betId());
            throw e;
        }
        return findBet(betMessage.betId());
    }

    @Transactional(readOnly = true)
    public Bet findBet(String betId) {
        return betRepository.findById(betId)
                .orElseThrow(() -> new BetNotFoundException(betId));
    }
}
// @GenAI-END
