// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service;

import com.sportsgroup.jackpot.api.dto.JackpotResponse;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.JackpotContribution;
import com.sportsgroup.jackpot.exception.JackpotNotFoundException;
import com.sportsgroup.jackpot.repository.JackpotContributionRepository;
import com.sportsgroup.jackpot.repository.JackpotRepository;
import com.sportsgroup.jackpot.service.contribution.ContributionCalculators;
import com.sportsgroup.jackpot.service.reward.RewardChanceCalculators;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Read-only views of jackpot state, including the contribution rate and win chance that
 * currently apply, so the effect of the variable strategies can be seen as a pool grows.
 */
@Service
@Transactional(readOnly = true)
public class JackpotQueryService {

    private final JackpotRepository jackpotRepository;
    private final JackpotContributionRepository contributionRepository;
    private final ContributionCalculators contributionCalculators;
    private final RewardChanceCalculators rewardChanceCalculators;

    public JackpotQueryService(JackpotRepository jackpotRepository,
                               JackpotContributionRepository contributionRepository,
                               ContributionCalculators contributionCalculators,
                               RewardChanceCalculators rewardChanceCalculators) {
        this.jackpotRepository = jackpotRepository;
        this.contributionRepository = contributionRepository;
        this.contributionCalculators = contributionCalculators;
        this.rewardChanceCalculators = rewardChanceCalculators;
    }

    public List<JackpotResponse> findAll() {
        return jackpotRepository.findAll().stream()
                .map(this::toResponse)
                .toList();
    }

    public JackpotResponse findById(String jackpotId) {
        return jackpotRepository.findById(jackpotId)
                .map(this::toResponse)
                .orElseThrow(() -> new JackpotNotFoundException(jackpotId));
    }

    public List<JackpotContribution> findContributions(String jackpotId) {
        if (!jackpotRepository.existsById(jackpotId)) {
            throw new JackpotNotFoundException(jackpotId);
        }
        return contributionRepository.findByJackpotIdOrderByCreatedAtAscIdAsc(jackpotId);
    }

    private JackpotResponse toResponse(Jackpot jackpot) {
        return new JackpotResponse(
                jackpot.getId(),
                jackpot.getName(),
                jackpot.getInitialPoolAmount(),
                jackpot.getCurrentPoolAmount(),
                jackpot.getContributionConfig().getType(),
                contributionCalculators.forType(jackpot.getContributionConfig().getType())
                        .contributionPercentage(jackpot),
                jackpot.getRewardConfig().getType(),
                rewardChanceCalculators.forType(jackpot.getRewardConfig().getType())
                        .winChancePercentage(jackpot));
    }
}
// @GenAI-END
