// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service;

import com.sportsgroup.jackpot.domain.Bet;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.JackpotContribution;
import com.sportsgroup.jackpot.domain.JackpotReward;
import com.sportsgroup.jackpot.exception.BetNotContributedException;
import com.sportsgroup.jackpot.exception.BetNotFoundException;
import com.sportsgroup.jackpot.exception.JackpotNotFoundException;
import com.sportsgroup.jackpot.repository.BetRepository;
import com.sportsgroup.jackpot.repository.JackpotContributionRepository;
import com.sportsgroup.jackpot.repository.JackpotRepository;
import com.sportsgroup.jackpot.repository.JackpotRewardRepository;
import com.sportsgroup.jackpot.service.reward.ChanceEvaluator;
import com.sportsgroup.jackpot.service.reward.RewardChanceCalculator;
import com.sportsgroup.jackpot.service.reward.RewardChanceCalculators;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.util.Optional;

/**
 * Use case 4: evaluate whether a contributing bet wins the jackpot reward.
 *
 * <p>Only a bet that actually contributed can win. On a win the whole pool is paid out,
 * the payout is recorded, and the pool is reset to its initial value, all inside one
 * transaction that holds a write lock on the jackpot.
 *
 * <p>A bet is evaluated at most once. Repeat calls replay the stored outcome instead of
 * rolling again, so a caller cannot retry a losing bet until it wins.
 */
@Service
public class RewardService {

    private static final Logger log = LoggerFactory.getLogger(RewardService.class);

    private final BetRepository betRepository;
    private final JackpotRepository jackpotRepository;
    private final JackpotContributionRepository contributionRepository;
    private final JackpotRewardRepository rewardRepository;
    private final RewardChanceCalculators rewardChanceCalculators;
    private final ChanceEvaluator chanceEvaluator;
    private final Clock clock;

    public RewardService(BetRepository betRepository,
                         JackpotRepository jackpotRepository,
                         JackpotContributionRepository contributionRepository,
                         JackpotRewardRepository rewardRepository,
                         RewardChanceCalculators rewardChanceCalculators,
                         ChanceEvaluator chanceEvaluator,
                         Clock clock) {
        this.betRepository = betRepository;
        this.jackpotRepository = jackpotRepository;
        this.contributionRepository = contributionRepository;
        this.rewardRepository = rewardRepository;
        this.rewardChanceCalculators = rewardChanceCalculators;
        this.chanceEvaluator = chanceEvaluator;
        this.clock = clock;
    }

    @Transactional
    public RewardEvaluation evaluate(String betId) {
        Bet bet = betRepository.findById(betId)
                .orElseThrow(() -> new BetNotFoundException(betId));

        JackpotContribution contribution = contributionRepository.findByBetId(betId)
                .orElseThrow(() -> new BetNotContributedException(betId));

        Optional<RewardEvaluation> storedOutcome = replayStoredOutcome(bet, contribution);
        if (storedOutcome.isPresent()) {
            return storedOutcome.get();
        }

        Jackpot jackpot = jackpotRepository.findByIdForUpdate(contribution.getJackpotId())
                .orElseThrow(() -> new JackpotNotFoundException(contribution.getJackpotId()));

        RewardChanceCalculator calculator =
                rewardChanceCalculators.forType(jackpot.getRewardConfig().getType());
        BigDecimal winChancePercentage = calculator.winChancePercentage(jackpot);

        Instant evaluatedAt = clock.instant();
        bet.markEvaluated(evaluatedAt);

        if (!chanceEvaluator.isWin(winChancePercentage)) {
            log.info("Bet {} did not win jackpot {} (chance was {}%)",
                    betId, jackpot.getId(), winChancePercentage);
            return new RewardEvaluation(
                    betId,
                    bet.getUserId(),
                    jackpot.getId(),
                    false,
                    BigDecimal.ZERO.setScale(2),
                    winChancePercentage,
                    jackpot.getCurrentPoolAmount(),
                    false,
                    evaluatedAt);
        }

        BigDecimal rewardAmount = jackpot.getCurrentPoolAmount();
        rewardRepository.save(new JackpotReward(
                betId, bet.getUserId(), jackpot.getId(), rewardAmount, evaluatedAt));
        jackpot.resetPool();

        log.info("Bet {} won {} from jackpot {} (chance was {}%), pool reset to {}",
                betId, rewardAmount, jackpot.getId(), winChancePercentage,
                jackpot.getCurrentPoolAmount());

        return new RewardEvaluation(
                betId,
                bet.getUserId(),
                jackpot.getId(),
                true,
                rewardAmount,
                winChancePercentage,
                jackpot.getCurrentPoolAmount(),
                false,
                evaluatedAt);
    }

    /**
     * Returns the previously stored outcome for a bet that has already been evaluated.
     */
    private Optional<RewardEvaluation> replayStoredOutcome(Bet bet, JackpotContribution contribution) {
        Optional<JackpotReward> existingReward = rewardRepository.findByBetId(bet.getId());
        if (existingReward.isPresent()) {
            JackpotReward reward = existingReward.get();
            return Optional.of(new RewardEvaluation(
                    reward.getBetId(),
                    reward.getUserId(),
                    reward.getJackpotId(),
                    true,
                    reward.getJackpotRewardAmount(),
                    null,
                    currentPoolAmount(reward.getJackpotId()),
                    true,
                    reward.getCreatedAt()));
        }

        if (bet.isEvaluated()) {
            return Optional.of(new RewardEvaluation(
                    bet.getId(),
                    bet.getUserId(),
                    contribution.getJackpotId(),
                    false,
                    BigDecimal.ZERO.setScale(2),
                    null,
                    currentPoolAmount(contribution.getJackpotId()),
                    true,
                    bet.getEvaluatedAt()));
        }

        return Optional.empty();
    }

    private BigDecimal currentPoolAmount(String jackpotId) {
        return jackpotRepository.findById(jackpotId)
                .map(Jackpot::getCurrentPoolAmount)
                .orElse(null);
    }
}
// @GenAI-END
