// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * The outcome of evaluating one bet for a jackpot reward.
 *
 * @param betId                    the evaluated bet
 * @param userId                   the user who placed it
 * @param jackpotId                the jackpot it contributed to
 * @param won                      whether the bet won the pool
 * @param rewardAmount             the amount paid out, or zero when the bet did not win
 * @param winChancePercentage      the chance used for this evaluation, null when replaying a
 *                                 previously stored outcome
 * @param jackpotPoolAmount        the pool amount after the evaluation, so a win visibly
 *                                 shows the pool back at its initial value
 * @param alreadyEvaluated         true when this bet had been evaluated before and the
 *                                 stored outcome is being returned instead of a new roll
 * @param evaluatedAt              when the bet was first evaluated
 */
public record RewardEvaluation(String betId,
                               String userId,
                               String jackpotId,
                               boolean won,
                               BigDecimal rewardAmount,
                               BigDecimal winChancePercentage,
                               BigDecimal jackpotPoolAmount,
                               boolean alreadyEvaluated,
                               Instant evaluatedAt) {
}
// @GenAI-END
