// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.config;

import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.Clock;

@Configuration
@EnableConfigurationProperties(JackpotProperties.class)
public class ApplicationConfig {

    /**
     * Time is injected rather than read statically so that persisted timestamps can be
     * asserted in tests.
     */
    @Bean
    public Clock clock() {
        return Clock.systemUTC();
    }
}
// @GenAI-END
