// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.config;

import com.sportsgroup.jackpot.domain.ContributionConfig;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.RewardConfig;
import com.sportsgroup.jackpot.repository.JackpotRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Loads the configured jackpots into the in-memory database on startup.
 *
 * <p>Existing jackpots are left untouched so a restart against a durable database would
 * never reset a live pool.
 */
@Component
public class JackpotSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(JackpotSeeder.class);

    private final JackpotProperties properties;
    private final JackpotRepository jackpotRepository;

    public JackpotSeeder(JackpotProperties properties, JackpotRepository jackpotRepository) {
        this.properties = properties;
        this.jackpotRepository = jackpotRepository;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        for (JackpotProperties.Definition definition : properties.getDefinitions()) {
            validate(definition);
            if (jackpotRepository.existsById(definition.getId())) {
                log.info("Jackpot {} already exists, leaving its pool untouched", definition.getId());
                continue;
            }
            jackpotRepository.save(toJackpot(definition));
            log.info("Seeded jackpot {} with initial pool {} (contribution={}, reward={})",
                    definition.getId(),
                    definition.getInitialPoolAmount(),
                    definition.getContribution().getType(),
                    definition.getReward().getType());
        }
    }

    private void validate(JackpotProperties.Definition definition) {
        if (definition.getId() == null || definition.getId().isBlank()) {
            throw new IllegalStateException("A configured jackpot is missing an id");
        }
        if (definition.getInitialPoolAmount() == null) {
            throw new IllegalStateException(
                    "Jackpot '" + definition.getId() + "' is missing initial-pool-amount");
        }
        if (definition.getContribution().getType() == null) {
            throw new IllegalStateException(
                    "Jackpot '" + definition.getId() + "' is missing contribution.type");
        }
        if (definition.getReward().getType() == null) {
            throw new IllegalStateException(
                    "Jackpot '" + definition.getId() + "' is missing reward.type");
        }
    }

    private Jackpot toJackpot(JackpotProperties.Definition definition) {
        JackpotProperties.Contribution contribution = definition.getContribution();
        JackpotProperties.Reward reward = definition.getReward();

        ContributionConfig contributionConfig = new ContributionConfig(
                contribution.getType(),
                contribution.getPercentage(),
                contribution.getMinPercentage(),
                contribution.getDecayPercentagePerStep(),
                contribution.getPoolStepAmount());

        RewardConfig rewardConfig = new RewardConfig(
                reward.getType(),
                reward.getChancePercentage(),
                reward.getChanceGrowthPercentagePerStep(),
                reward.getPoolStepAmount(),
                reward.getGuaranteedPoolLimit());

        return new Jackpot(
                definition.getId(),
                definition.getName() == null ? definition.getId() : definition.getName(),
                definition.getInitialPoolAmount(),
                contributionConfig,
                rewardConfig);
    }
}
// @GenAI-END
