// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.config;

import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.RewardType;
import org.springframework.boot.context.properties.ConfigurationProperties;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Externalised jackpot configuration bound from {@code jackpot.*}.
 *
 * <p>Every jackpot declares its own initial pool value, contribution configuration and
 * reward configuration, so operators can add jackpots or retune existing ones without a
 * code change.
 */
@ConfigurationProperties(prefix = "jackpot")
public class JackpotProperties {

    private final Kafka kafka = new Kafka();
    private List<Definition> definitions = new ArrayList<>();

    public Kafka getKafka() {
        return kafka;
    }

    public List<Definition> getDefinitions() {
        return definitions;
    }

    public void setDefinitions(List<Definition> definitions) {
        this.definitions = definitions;
    }

    public static class Kafka {

        /** When false the mock publisher is used and no broker is required. */
        private boolean enabled = false;

        private String topic = "jackpot-bets";

        public boolean isEnabled() {
            return enabled;
        }

        public void setEnabled(boolean enabled) {
            this.enabled = enabled;
        }

        public String getTopic() {
            return topic;
        }

        public void setTopic(String topic) {
            this.topic = topic;
        }
    }

    public static class Definition {

        private String id;
        private String name;
        private BigDecimal initialPoolAmount;
        private Contribution contribution = new Contribution();
        private Reward reward = new Reward();

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public BigDecimal getInitialPoolAmount() {
            return initialPoolAmount;
        }

        public void setInitialPoolAmount(BigDecimal initialPoolAmount) {
            this.initialPoolAmount = initialPoolAmount;
        }

        public Contribution getContribution() {
            return contribution;
        }

        public void setContribution(Contribution contribution) {
            this.contribution = contribution;
        }

        public Reward getReward() {
            return reward;
        }

        public void setReward(Reward reward) {
            this.reward = reward;
        }
    }

    public static class Contribution {

        private ContributionType type;
        private BigDecimal percentage;
        private BigDecimal minPercentage;
        private BigDecimal decayPercentagePerStep;
        private BigDecimal poolStepAmount;

        public ContributionType getType() {
            return type;
        }

        public void setType(ContributionType type) {
            this.type = type;
        }

        public BigDecimal getPercentage() {
            return percentage;
        }

        public void setPercentage(BigDecimal percentage) {
            this.percentage = percentage;
        }

        public BigDecimal getMinPercentage() {
            return minPercentage;
        }

        public void setMinPercentage(BigDecimal minPercentage) {
            this.minPercentage = minPercentage;
        }

        public BigDecimal getDecayPercentagePerStep() {
            return decayPercentagePerStep;
        }

        public void setDecayPercentagePerStep(BigDecimal decayPercentagePerStep) {
            this.decayPercentagePerStep = decayPercentagePerStep;
        }

        public BigDecimal getPoolStepAmount() {
            return poolStepAmount;
        }

        public void setPoolStepAmount(BigDecimal poolStepAmount) {
            this.poolStepAmount = poolStepAmount;
        }
    }

    public static class Reward {

        private RewardType type;
        private BigDecimal chancePercentage;
        private BigDecimal chanceGrowthPercentagePerStep;
        private BigDecimal poolStepAmount;
        private BigDecimal guaranteedPoolLimit;

        public RewardType getType() {
            return type;
        }

        public void setType(RewardType type) {
            this.type = type;
        }

        public BigDecimal getChancePercentage() {
            return chancePercentage;
        }

        public void setChancePercentage(BigDecimal chancePercentage) {
            this.chancePercentage = chancePercentage;
        }

        public BigDecimal getChanceGrowthPercentagePerStep() {
            return chanceGrowthPercentagePerStep;
        }

        public void setChanceGrowthPercentagePerStep(BigDecimal chanceGrowthPercentagePerStep) {
            this.chanceGrowthPercentagePerStep = chanceGrowthPercentagePerStep;
        }

        public BigDecimal getPoolStepAmount() {
            return poolStepAmount;
        }

        public void setPoolStepAmount(BigDecimal poolStepAmount) {
            this.poolStepAmount = poolStepAmount;
        }

        public BigDecimal getGuaranteedPoolLimit() {
            return guaranteedPoolLimit;
        }

        public void setGuaranteedPoolLimit(BigDecimal guaranteedPoolLimit) {
            this.guaranteedPoolLimit = guaranteedPoolLimit;
        }
    }
}
// @GenAI-END
