// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.config;

import org.apache.kafka.clients.admin.NewTopic;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.kafka.config.TopicBuilder;

/**
 * Creates the {@code jackpot-bets} topic on startup when running against a real broker.
 */
@Configuration
@ConditionalOnProperty(name = "jackpot.kafka.enabled", havingValue = "true")
public class KafkaTopicConfig {

    @Bean
    public NewTopic jackpotBetsTopic(JackpotProperties properties) {
        return TopicBuilder.name(properties.getKafka().getTopic())
                .partitions(3)
                .replicas(1)
                .build();
    }
}
// @GenAI-END
