// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.exception;

/**
 * Raised when a bet exists but has not contributed to a jackpot, so it cannot win one.
 *
 * <p>Either the bet has not been consumed yet or its jackpot id matched no jackpot.
 */
public class BetNotContributedException extends RuntimeException {

    public BetNotContributedException(String betId) {
        super("Bet '" + betId + "' has not contributed to a jackpot and cannot be evaluated for a reward");
    }
}
// @GenAI-END
