// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.exception;

/**
 * Raised when a reward evaluation references a bet the service has never seen.
 */
public class BetNotFoundException extends RuntimeException {

    public BetNotFoundException(String betId) {
        super("Bet '" + betId + "' was not found");
    }
}
// @GenAI-END
