// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.exception;

/**
 * Raised when a bet could not be handed to the messaging layer.
 */
public class BetPublishFailedException extends RuntimeException {

    public BetPublishFailedException(String betId, Throwable cause) {
        super("Failed to publish bet '" + betId + "'", cause);
    }
}
// @GenAI-END
