// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.exception;

/**
 * Raised when a bet id that has already been accepted is submitted again.
 */
public class DuplicateBetException extends RuntimeException {

    public DuplicateBetException(String betId) {
        super("Bet '" + betId + "' has already been published");
    }
}
// @GenAI-END
