// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.exception;

/**
 * Raised when a jackpot id does not match any configured jackpot.
 */
public class JackpotNotFoundException extends RuntimeException {

    public JackpotNotFoundException(String jackpotId) {
        super("Jackpot '" + jackpotId + "' was not found");
    }
}
// @GenAI-END
