// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.contribution;

import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.support.Percentages;

import java.math.BigDecimal;

/**
 * Works out how much of a stake goes into a jackpot pool.
 *
 * <p>Each implementation declares the {@link ContributionType} it handles and is picked up
 * automatically by {@link ContributionCalculators}. Supporting a new contribution model is
 * therefore a new enum constant plus a new bean, with no changes to the calling code.
 */
public interface ContributionCalculator {

    ContributionType type();

    /**
     * The percentage of the stake this jackpot currently contributes. Exposed separately
     * from the amount so the API can explain how a contribution was derived.
     */
    BigDecimal contributionPercentage(Jackpot jackpot);

    /**
     * The contribution amount for the given stake, rounded to 2 decimals.
     */
    default BigDecimal contributionAmount(Jackpot jackpot, BigDecimal stakeAmount) {
        return Percentages.applyTo(contributionPercentage(jackpot), stakeAmount);
    }
}
// @GenAI-END
