// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.contribution;

import com.sportsgroup.jackpot.domain.ContributionType;
import org.springframework.stereotype.Component;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * Resolves the calculator for a jackpot's contribution type.
 *
 * <p>Spring injects every {@link ContributionCalculator} bean on the classpath, so a new
 * contribution model becomes available simply by declaring it as a component.
 */
@Component
public class ContributionCalculators {

    private final Map<ContributionType, ContributionCalculator> calculatorsByType =
            new EnumMap<>(ContributionType.class);

    public ContributionCalculators(List<ContributionCalculator> calculators) {
        for (ContributionCalculator calculator : calculators) {
            ContributionCalculator previous = calculatorsByType.put(calculator.type(), calculator);
            if (previous != null) {
                throw new IllegalStateException(
                        "Two contribution calculators registered for type " + calculator.type());
            }
        }
    }

    public ContributionCalculator forType(ContributionType type) {
        ContributionCalculator calculator = calculatorsByType.get(type);
        if (calculator == null) {
            throw new IllegalStateException("No contribution calculator registered for type " + type);
        }
        return calculator;
    }
}
// @GenAI-END
