// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.contribution;

import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.support.Percentages;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

/**
 * Contributes a constant percentage of the stake, whatever the pool is worth.
 */
@Component
public class FixedContributionCalculator implements ContributionCalculator {

    @Override
    public ContributionType type() {
        return ContributionType.FIXED;
    }

    @Override
    public BigDecimal contributionPercentage(Jackpot jackpot) {
        BigDecimal percentage = Percentages.required(
                jackpot.getContributionConfig().getPercentage(), jackpot.getId(), "contribution.percentage");
        return Percentages.normalise(percentage);
    }
}
// @GenAI-END
