// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.contribution;

import com.sportsgroup.jackpot.domain.ContributionConfig;
import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.support.Percentages;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

/**
 * Contributes a percentage that starts high and falls at a fixed rate as the pool grows,
 * so an empty jackpot fills quickly and a large one grows slowly.
 *
 * <pre>
 *   growth     = currentPool - initialPool
 *   steps      = growth / poolStepAmount
 *   percentage = max(minPercentage, startPercentage - decayPercentagePerStep * steps)
 * </pre>
 *
 * <p>With a 10% start, a 1 percentage point decay and a 10,000 step, a pool that has grown
 * by 25,000 contributes 7.5%, and the rate never drops below the configured minimum.
 */
@Component
public class VariableContributionCalculator implements ContributionCalculator {

    @Override
    public ContributionType type() {
        return ContributionType.VARIABLE;
    }

    @Override
    public BigDecimal contributionPercentage(Jackpot jackpot) {
        ContributionConfig config = jackpot.getContributionConfig();
        String jackpotId = jackpot.getId();

        BigDecimal startPercentage = Percentages.required(
                config.getPercentage(), jackpotId, "contribution.percentage");
        BigDecimal minPercentage = Percentages.required(
                config.getMinPercentage(), jackpotId, "contribution.min-percentage");
        BigDecimal decayPerStep = Percentages.required(
                config.getDecayPercentagePerStep(), jackpotId, "contribution.decay-percentage-per-step");
        BigDecimal poolStepAmount = Percentages.required(
                config.getPoolStepAmount(), jackpotId, "contribution.pool-step-amount");

        BigDecimal steps = Percentages.steps(jackpot.poolGrowth(), poolStepAmount);
        BigDecimal decayed = startPercentage.subtract(decayPerStep.multiply(steps));

        return Percentages.clamp(decayed, minPercentage, startPercentage);
    }
}
// @GenAI-END
