// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.support;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Percentage and money arithmetic shared by the contribution and reward calculators.
 *
 * <p>All monetary results are rounded to 2 decimals and all percentages to 4, so the same
 * inputs always produce byte-identical amounts.
 */
public final class Percentages {

    public static final BigDecimal ZERO = BigDecimal.ZERO;
    public static final BigDecimal ONE_HUNDRED = new BigDecimal("100");

    private static final int MONEY_SCALE = 2;
    private static final int PERCENTAGE_SCALE = 4;
    private static final int STEP_SCALE = 10;

    private Percentages() {
    }

    /**
     * Applies a percentage to an amount, e.g. 5% of 100.00 is 5.00.
     */
    public static BigDecimal applyTo(BigDecimal percentage, BigDecimal amount) {
        return amount.multiply(percentage)
                .divide(ONE_HUNDRED, MONEY_SCALE, RoundingMode.HALF_UP);
    }

    /**
     * How many steps of {@code stepAmount} fit into {@code growth}, as a fraction so the
     * curve moves smoothly rather than jumping at step boundaries.
     */
    public static BigDecimal steps(BigDecimal growth, BigDecimal stepAmount) {
        if (stepAmount.signum() <= 0) {
            return ZERO;
        }
        return growth.max(ZERO).divide(stepAmount, STEP_SCALE, RoundingMode.HALF_UP);
    }

    /**
     * Constrains a percentage to {@code [lowerBound, upperBound]} at percentage scale.
     */
    public static BigDecimal clamp(BigDecimal percentage, BigDecimal lowerBound, BigDecimal upperBound) {
        return percentage.max(lowerBound)
                .min(upperBound)
                .setScale(PERCENTAGE_SCALE, RoundingMode.HALF_UP);
    }

    /**
     * Rounds a percentage for reporting without changing its value meaningfully.
     */
    public static BigDecimal normalise(BigDecimal percentage) {
        return percentage.setScale(PERCENTAGE_SCALE, RoundingMode.HALF_UP);
    }

    /**
     * Guards against a jackpot being configured without a value its strategy needs.
     */
    public static BigDecimal required(BigDecimal value, String jackpotId, String property) {
        if (value == null) {
            throw new IllegalStateException(
                    "Jackpot '" + jackpotId + "' is missing required configuration '" + property + "'");
        }
        return value;
    }
}
// @GenAI-END
