// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.sportsgroup.jackpot.api.dto.BetResponse;
import com.sportsgroup.jackpot.api.dto.ContributionResponse;
import com.sportsgroup.jackpot.api.dto.JackpotResponse;
import com.sportsgroup.jackpot.api.dto.RewardEvaluationResponse;
import com.sportsgroup.jackpot.config.JackpotSeeder;
import com.sportsgroup.jackpot.domain.BetStatus;
import com.sportsgroup.jackpot.messaging.BetMessage;
import com.sportsgroup.jackpot.repository.BetRepository;
import com.sportsgroup.jackpot.repository.JackpotContributionRepository;
import com.sportsgroup.jackpot.repository.JackpotRepository;
import com.sportsgroup.jackpot.repository.JackpotRewardRepository;
import com.sportsgroup.jackpot.service.BetProcessingService;
import com.sportsgroup.jackpot.service.reward.ChanceEvaluator;
import com.sportsgroup.jackpot.support.ControllableChanceEvaluator;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.math.BigDecimal;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Covers the whole flow the requirements describe, from the publish endpoint through the
 * consumer and the persistence layer to the reward endpoint.
 *
 * <p>Runs against the default configuration, so the mock publisher hands each bet to the
 * same processing code the Kafka listener uses.
 */
@SpringBootTest
@AutoConfigureMockMvc
class JackpotFlowIntegrationTest {

    private static final String FIXED_JACKPOT = "jackpot-fixed-1";
    private static final String VARIABLE_JACKPOT = "jackpot-variable-1";

    @TestConfiguration
    static class DeterministicChanceConfiguration {

        @Bean
        @Primary
        ChanceEvaluator controllableChanceEvaluator() {
            return new ControllableChanceEvaluator();
        }
    }

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private BetProcessingService betProcessingService;

    @Autowired
    private JackpotSeeder jackpotSeeder;

    @Autowired
    private BetRepository betRepository;

    @Autowired
    private JackpotRepository jackpotRepository;

    @Autowired
    private JackpotContributionRepository contributionRepository;

    @Autowired
    private JackpotRewardRepository rewardRepository;

    @Autowired
    private ChanceEvaluator chanceEvaluator;

    private ControllableChanceEvaluator chance;

    @BeforeEach
    void resetState() {
        rewardRepository.deleteAll();
        contributionRepository.deleteAll();
        betRepository.deleteAll();
        jackpotRepository.deleteAll();
        jackpotSeeder.run(null);

        chance = (ControllableChanceEvaluator) chanceEvaluator;
        chance.reset();
    }

    @Test
    @DisplayName("a published bet contributes to its matching jackpot pool")
    void publishedBetContributesToMatchingJackpotPool() throws Exception {
        BetResponse bet = publishBet("bet-1", "user-1", FIXED_JACKPOT, "100.00");

        assertThat(bet.status()).isEqualTo(BetStatus.CONTRIBUTED);

        // 5% of 100.00 on a 10,000.00 pool
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10005.00");

        List<ContributionResponse> contributions = contributions(FIXED_JACKPOT);
        assertThat(contributions).hasSize(1);
        ContributionResponse contribution = contributions.getFirst();
        assertThat(contribution.betId()).isEqualTo("bet-1");
        assertThat(contribution.userId()).isEqualTo("user-1");
        assertThat(contribution.jackpotId()).isEqualTo(FIXED_JACKPOT);
        assertThat(contribution.stakeAmount()).isEqualByComparingTo("100.00");
        assertThat(contribution.contributionAmount()).isEqualByComparingTo("5.00");
        assertThat(contribution.currentJackpotAmount()).isEqualByComparingTo("10005.00");
        assertThat(contribution.createdAt()).isNotNull();
    }

    @Test
    @DisplayName("a variable jackpot contributes a smaller share as its pool grows")
    void variableJackpotContributesSmallerShareAsPoolGrows() throws Exception {
        publishBet("bet-v1", "user-1", VARIABLE_JACKPOT, "1000.00");

        // Pool has not grown yet, so the full 10% applies: 50,000.00 + 100.00
        assertThat(jackpot(VARIABLE_JACKPOT).currentPoolAmount()).isEqualByComparingTo("50100.00");

        publishBet("bet-v2", "user-1", VARIABLE_JACKPOT, "1000.00");

        // Growth of 100.00 is a hundredth of a 10,000.00 step, so the rate is now 9.99%
        assertThat(jackpot(VARIABLE_JACKPOT).currentPoolAmount()).isEqualByComparingTo("50199.90");

        List<ContributionResponse> contributions = contributions(VARIABLE_JACKPOT);
        assertThat(contributions).hasSize(2);
        assertThat(contributions.get(0).contributionAmount()).isEqualByComparingTo("100.00");
        assertThat(contributions.get(1).contributionAmount()).isEqualByComparingTo("99.90");
    }

    @Test
    @DisplayName("a winning bet is paid the whole pool and the pool is reset")
    void winningBetIsPaidTheWholePoolAndResetsIt() throws Exception {
        publishBet("bet-2", "user-2", FIXED_JACKPOT, "100.00");
        chance.alwaysWin();

        RewardEvaluationResponse evaluation = evaluate("bet-2");

        assertThat(evaluation.won()).isTrue();
        assertThat(evaluation.rewardAmount()).isEqualByComparingTo("10005.00");
        assertThat(evaluation.jackpotId()).isEqualTo(FIXED_JACKPOT);
        assertThat(evaluation.userId()).isEqualTo("user-2");
        assertThat(evaluation.alreadyEvaluated()).isFalse();

        // The fixed jackpot is configured with a 10% chance, which is what was evaluated
        assertThat(chance.lastEvaluatedChance()).isEqualByComparingTo("10");

        // Reset to the configured initial pool value
        assertThat(evaluation.jackpotPoolAmount()).isEqualByComparingTo("10000.00");
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10000.00");

        assertThat(rewardRepository.findByBetId("bet-2")).isPresent().get()
                .satisfies(reward -> {
                    assertThat(reward.getJackpotRewardAmount()).isEqualByComparingTo("10005.00");
                    assertThat(reward.getUserId()).isEqualTo("user-2");
                    assertThat(reward.getCreatedAt()).isNotNull();
                });
    }

    @Test
    @DisplayName("a losing bet returns no reward and leaves the pool alone")
    void losingBetReturnsNoRewardAndLeavesPoolAlone() throws Exception {
        publishBet("bet-3", "user-3", FIXED_JACKPOT, "100.00");
        chance.neverWin();

        RewardEvaluationResponse evaluation = evaluate("bet-3");

        assertThat(evaluation.won()).isFalse();
        assertThat(evaluation.rewardAmount()).isEqualByComparingTo("0.00");
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10005.00");
        assertThat(rewardRepository.findByBetId("bet-3")).isEmpty();
    }

    @Test
    @DisplayName("a bet is evaluated once and repeat calls replay the stored outcome")
    void betIsEvaluatedOnceAndRepeatCallsReplayStoredOutcome() throws Exception {
        publishBet("bet-4", "user-4", FIXED_JACKPOT, "100.00");
        chance.neverWin();
        evaluate("bet-4");

        // Even with a guaranteed win now, the bet must not get a second roll
        chance.alwaysWin();
        RewardEvaluationResponse replay = evaluate("bet-4");

        assertThat(replay.alreadyEvaluated()).isTrue();
        assertThat(replay.won()).isFalse();
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10005.00");
    }

    @Test
    @DisplayName("a won bet replays the same reward instead of paying twice")
    void wonBetReplaysSameRewardInsteadOfPayingTwice() throws Exception {
        publishBet("bet-5", "user-5", FIXED_JACKPOT, "100.00");
        chance.alwaysWin();
        evaluate("bet-5");

        RewardEvaluationResponse replay = evaluate("bet-5");

        assertThat(replay.alreadyEvaluated()).isTrue();
        assertThat(replay.won()).isTrue();
        assertThat(replay.rewardAmount()).isEqualByComparingTo("10005.00");
        assertThat(rewardRepository.count()).isEqualTo(1);
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10000.00");
    }

    @Test
    @DisplayName("a redelivered bet contributes only once")
    void redeliveredBetContributesOnlyOnce() throws Exception {
        BetMessage message = new BetMessage("bet-6", "user-6", FIXED_JACKPOT, new BigDecimal("100.00"));

        betProcessingService.process(message);
        betProcessingService.process(message);

        assertThat(contributionRepository.count()).isEqualTo(1);
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10005.00");
    }

    @Test
    @DisplayName("a bet for an unknown jackpot is accepted but contributes nothing")
    void betForUnknownJackpotIsAcceptedButContributesNothing() throws Exception {
        BetResponse bet = publishBet("bet-7", "user-7", "jackpot-does-not-exist", "100.00");

        assertThat(bet.status()).isEqualTo(BetStatus.NO_MATCHING_JACKPOT);
        assertThat(contributionRepository.count()).isZero();

        mockMvc.perform(post("/api/v1/bets/{betId}/evaluate", "bet-7"))
                .andExpect(status().isUnprocessableEntity())
                .andExpect(jsonPath("$.message").value(
                        "Bet 'bet-7' has not contributed to a jackpot and cannot be evaluated for a reward"));
    }

    @Test
    @DisplayName("a variable jackpot guarantees a win once its pool limit is reached")
    void variableJackpotGuaranteesWinOncePoolLimitIsReached() throws Exception {
        // 10% of 500,000.00 takes the 50,000.00 pool to exactly the 100,000.00 limit
        publishBet("bet-8", "user-8", VARIABLE_JACKPOT, "500000.00");

        JackpotResponse jackpot = jackpot(VARIABLE_JACKPOT);
        assertThat(jackpot.currentPoolAmount()).isEqualByComparingTo("100000.00");
        assertThat(jackpot.currentWinChancePercentage()).isEqualByComparingTo("100");
        assertThat(jackpot.currentContributionPercentage()).isEqualByComparingTo("5");
    }

    @Test
    @DisplayName("the same bet id cannot be published twice")
    void sameBetIdCannotBePublishedTwice() throws Exception {
        publishBet("bet-9", "user-9", FIXED_JACKPOT, "100.00");

        mockMvc.perform(post("/api/v1/bets")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(betJson("bet-9", "user-9", FIXED_JACKPOT, "100.00")))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.message").value("Bet 'bet-9' has already been published"));

        assertThat(contributionRepository.count()).isEqualTo(1);
    }

    @Test
    @DisplayName("an invalid bet is rejected with the failing fields")
    void invalidBetIsRejectedWithFailingFields() throws Exception {
        String invalid = """
                {"betId":"","userId":"user-1","jackpotId":"%s","betAmount":-5}
                """.formatted(FIXED_JACKPOT);

        mockMvc.perform(post("/api/v1/bets")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(invalid))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.details", Matchers.hasSize(2)))
                .andExpect(jsonPath("$.details[0]").value("betAmount must be greater than zero"))
                .andExpect(jsonPath("$.details[1]").value("betId is required"));
    }

    @Test
    @DisplayName("evaluating an unknown bet returns not found")
    void evaluatingUnknownBetReturnsNotFound() throws Exception {
        mockMvc.perform(post("/api/v1/bets/{betId}/evaluate", "no-such-bet"))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message").value("Bet 'no-such-bet' was not found"));
    }

    @Test
    @DisplayName("the configured jackpots are seeded with their initial pool values")
    void configuredJackpotsAreSeededWithInitialPoolValues() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/jackpots"))
                .andExpect(status().isOk())
                .andReturn();

        List<JackpotResponse> jackpots = objectMapper.readValue(
                result.getResponse().getContentAsString(), new TypeReference<>() {
                });

        assertThat(jackpots)
                .extracting(JackpotResponse::jackpotId)
                .containsExactlyInAnyOrder(FIXED_JACKPOT, VARIABLE_JACKPOT);
        assertThat(jackpot(FIXED_JACKPOT).currentPoolAmount()).isEqualByComparingTo("10000.00");
        assertThat(jackpot(VARIABLE_JACKPOT).currentPoolAmount()).isEqualByComparingTo("50000.00");
    }

    private BetResponse publishBet(String betId, String userId, String jackpotId, String amount)
            throws Exception {
        MvcResult result = mockMvc.perform(post("/api/v1/bets")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(betJson(betId, userId, jackpotId, amount)))
                .andExpect(status().isAccepted())
                .andReturn();
        return objectMapper.readValue(result.getResponse().getContentAsString(), BetResponse.class);
    }

    private RewardEvaluationResponse evaluate(String betId) throws Exception {
        MvcResult result = mockMvc.perform(post("/api/v1/bets/{betId}/evaluate", betId))
                .andExpect(status().isOk())
                .andReturn();
        return objectMapper.readValue(
                result.getResponse().getContentAsString(), RewardEvaluationResponse.class);
    }

    private JackpotResponse jackpot(String jackpotId) throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/jackpots/{jackpotId}", jackpotId))
                .andExpect(status().isOk())
                .andReturn();
        return objectMapper.readValue(result.getResponse().getContentAsString(), JackpotResponse.class);
    }

    private List<ContributionResponse> contributions(String jackpotId) throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/jackpots/{jackpotId}/contributions", jackpotId))
                .andExpect(status().isOk())
                .andReturn();
        return objectMapper.readValue(
                result.getResponse().getContentAsString(), new TypeReference<>() {
                });
    }

    private String betJson(String betId, String userId, String jackpotId, String amount) {
        return """
                {"betId":"%s","userId":"%s","jackpotId":"%s","betAmount":%s}
                """.formatted(betId, userId, jackpotId, amount);
    }
}
// @GenAI-END
