// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.contribution;

import com.sportsgroup.jackpot.domain.ContributionConfig;
import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.support.JackpotFixtures;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class FixedContributionCalculatorTest {

    private final FixedContributionCalculator calculator = new FixedContributionCalculator();

    @Test
    @DisplayName("contributes the configured percentage of the stake")
    void contributesConfiguredPercentageOfStake() {
        Jackpot jackpot = JackpotFixtures.fixedContribution("10000.00", "5");

        assertThat(calculator.contributionAmount(jackpot, new BigDecimal("100.00")))
                .isEqualByComparingTo("5.00");
        assertThat(calculator.contributionAmount(jackpot, new BigDecimal("250.00")))
                .isEqualByComparingTo("12.50");
    }

    @Test
    @DisplayName("keeps the same percentage however large the pool grows")
    void keepsSamePercentageAsPoolGrows() {
        Jackpot jackpot = JackpotFixtures.fixedContribution("10000.00", "5");
        BigDecimal beforeGrowth = calculator.contributionPercentage(jackpot);

        JackpotFixtures.grownBy(jackpot, "500000.00");

        assertThat(calculator.contributionPercentage(jackpot)).isEqualByComparingTo(beforeGrowth);
    }

    @Test
    @DisplayName("rounds the contribution to two decimals, half up")
    void roundsContributionToTwoDecimals() {
        Jackpot jackpot = JackpotFixtures.fixedContribution("10000.00", "7.5");

        // 7.5% of 33.33 is 2.49975
        assertThat(calculator.contributionAmount(jackpot, new BigDecimal("33.33")))
                .isEqualByComparingTo("2.50");
    }

    @Test
    @DisplayName("fails fast when the jackpot has no contribution percentage configured")
    void failsWhenPercentageMissing() {
        Jackpot template = JackpotFixtures.fixedContribution("10000.00", "5");
        Jackpot withoutPercentage = new Jackpot(
                template.getId(),
                template.getName(),
                template.getInitialPoolAmount(),
                new ContributionConfig(ContributionType.FIXED, null, null, null, null),
                template.getRewardConfig());

        assertThatThrownBy(() -> calculator.contributionPercentage(withoutPercentage))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("contribution.percentage");
    }
}
// @GenAI-END
