// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.contribution;

import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.support.JackpotFixtures;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.math.BigDecimal;

import static org.assertj.core.api.Assertions.assertThat;

class VariableContributionCalculatorTest {

    private final VariableContributionCalculator calculator = new VariableContributionCalculator();

    /**
     * Starts at 10%, loses 1 percentage point per 10,000 of pool growth, floor of 1%.
     */
    private Jackpot jackpot() {
        return JackpotFixtures.variableContribution("0.00", "10", "1", "1", "10000.00");
    }

    @Test
    @DisplayName("contributes the starting percentage while the pool has not grown")
    void usesStartingPercentageOnFreshPool() {
        assertThat(calculator.contributionPercentage(jackpot())).isEqualByComparingTo("10");
    }

    @ParameterizedTest(name = "pool grown by {0} contributes {1}%")
    @CsvSource({
            "0.00,      10",
            "10000.00,   9",
            "25000.00, 7.5",
            "50000.00,   5",
            "90000.00,   1"
    })
    @DisplayName("lowers the percentage at a fixed rate as the pool grows")
    void lowersPercentageAsPoolGrows(String growth, String expectedPercentage) {
        Jackpot jackpot = JackpotFixtures.grownBy(jackpot(), growth);

        assertThat(calculator.contributionPercentage(jackpot)).isEqualByComparingTo(expectedPercentage);
    }

    @Test
    @DisplayName("never drops below the configured minimum percentage")
    void neverDropsBelowMinimum() {
        Jackpot jackpot = JackpotFixtures.grownBy(jackpot(), "5000000.00");

        assertThat(calculator.contributionPercentage(jackpot)).isEqualByComparingTo("1");
    }

    @Test
    @DisplayName("applies the decayed percentage to the stake")
    void appliesDecayedPercentageToStake() {
        Jackpot jackpot = JackpotFixtures.grownBy(jackpot(), "25000.00");

        // 7.5% of 200.00
        assertThat(calculator.contributionAmount(jackpot, new BigDecimal("200.00")))
                .isEqualByComparingTo("15.00");
    }

    @Test
    @DisplayName("treats a pool below its initial value as no growth")
    void treatsPoolBelowInitialValueAsNoGrowth() {
        Jackpot jackpot = JackpotFixtures.variableContribution("50000.00", "10", "1", "1", "10000.00");

        assertThat(calculator.contributionPercentage(jackpot)).isEqualByComparingTo("10");
    }
}
// @GenAI-END
