// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import java.math.BigDecimal;

/**
 * Decides whether a given win chance actually wins.
 *
 * <p>Randomness sits behind this interface so that the reward flow can be tested
 * deterministically by substituting an always-win or never-win implementation.
 */
public interface ChanceEvaluator {

    boolean isWin(BigDecimal winChancePercentage);
}
// @GenAI-END
