// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.RewardType;
import com.sportsgroup.jackpot.support.Percentages;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

/**
 * Gives every evaluated bet the same win chance, whatever the pool is worth.
 */
@Component
public class FixedRewardChanceCalculator implements RewardChanceCalculator {

    @Override
    public RewardType type() {
        return RewardType.FIXED;
    }

    @Override
    public BigDecimal winChancePercentage(Jackpot jackpot) {
        BigDecimal chance = Percentages.required(
                jackpot.getRewardConfig().getChancePercentage(), jackpot.getId(), "reward.chance-percentage");
        return Percentages.clamp(chance, Percentages.ZERO, Percentages.ONE_HUNDRED);
    }
}
// @GenAI-END
