// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import com.sportsgroup.jackpot.support.Percentages;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Draws a uniform number in [0, 100) and wins when it falls below the chance.
 */
@Component
public class RandomChanceEvaluator implements ChanceEvaluator {

    @Override
    public boolean isWin(BigDecimal winChancePercentage) {
        if (winChancePercentage.signum() <= 0) {
            return false;
        }
        if (winChancePercentage.compareTo(Percentages.ONE_HUNDRED) >= 0) {
            return true;
        }
        BigDecimal roll = BigDecimal.valueOf(ThreadLocalRandom.current().nextDouble(100.0d));
        return roll.compareTo(winChancePercentage) < 0;
    }
}
// @GenAI-END
