// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import com.sportsgroup.jackpot.domain.RewardType;
import org.springframework.stereotype.Component;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * Resolves the calculator for a jackpot's reward type.
 *
 * <p>Spring injects every {@link RewardChanceCalculator} bean on the classpath, so a new
 * reward model becomes available simply by declaring it as a component.
 */
@Component
public class RewardChanceCalculators {

    private final Map<RewardType, RewardChanceCalculator> calculatorsByType =
            new EnumMap<>(RewardType.class);

    public RewardChanceCalculators(List<RewardChanceCalculator> calculators) {
        for (RewardChanceCalculator calculator : calculators) {
            RewardChanceCalculator previous = calculatorsByType.put(calculator.type(), calculator);
            if (previous != null) {
                throw new IllegalStateException(
                        "Two reward chance calculators registered for type " + calculator.type());
            }
        }
    }

    public RewardChanceCalculator forType(RewardType type) {
        RewardChanceCalculator calculator = calculatorsByType.get(type);
        if (calculator == null) {
            throw new IllegalStateException("No reward chance calculator registered for type " + type);
        }
        return calculator;
    }
}
// @GenAI-END
