// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.RewardType;

import java.math.BigDecimal;

/**
 * Works out the chance, as a percentage between 0 and 100, that a bet wins a jackpot.
 *
 * <p>Each implementation declares the {@link RewardType} it handles and is picked up
 * automatically by {@link RewardChanceCalculators}. Supporting a new reward model is
 * therefore a new enum constant plus a new bean, with no changes to the calling code.
 */
public interface RewardChanceCalculator {

    RewardType type();

    BigDecimal winChancePercentage(Jackpot jackpot);
}
// @GenAI-END
