// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.RewardConfig;
import com.sportsgroup.jackpot.domain.RewardType;
import com.sportsgroup.jackpot.support.Percentages;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;

/**
 * Gives a win chance that starts low and grows at a fixed rate as the pool grows, so a
 * jackpot cannot keep growing forever.
 *
 * <pre>
 *   if currentPool >= guaranteedPoolLimit -> 100%
 *   growth = currentPool - initialPool
 *   steps  = growth / poolStepAmount
 *   chance = min(100, startChance + chanceGrowthPercentagePerStep * steps)
 * </pre>
 *
 * <p>With a 1% start, 5 percentage points of growth and a 10,000 step, a pool that has
 * grown by 25,000 wins 13.5% of the time, and the pool limit acts as a hard ceiling.
 */
@Component
public class VariableRewardChanceCalculator implements RewardChanceCalculator {

    @Override
    public RewardType type() {
        return RewardType.VARIABLE;
    }

    @Override
    public BigDecimal winChancePercentage(Jackpot jackpot) {
        RewardConfig config = jackpot.getRewardConfig();
        String jackpotId = jackpot.getId();

        BigDecimal guaranteedPoolLimit = config.getGuaranteedPoolLimit();
        if (guaranteedPoolLimit != null
                && jackpot.getCurrentPoolAmount().compareTo(guaranteedPoolLimit) >= 0) {
            return Percentages.normalise(Percentages.ONE_HUNDRED);
        }

        BigDecimal startChance = Percentages.required(
                config.getChancePercentage(), jackpotId, "reward.chance-percentage");
        BigDecimal growthPerStep = Percentages.required(
                config.getChanceGrowthPercentagePerStep(), jackpotId, "reward.chance-growth-percentage-per-step");
        BigDecimal poolStepAmount = Percentages.required(
                config.getPoolStepAmount(), jackpotId, "reward.pool-step-amount");

        BigDecimal steps = Percentages.steps(jackpot.poolGrowth(), poolStepAmount);
        BigDecimal grown = startChance.add(growthPerStep.multiply(steps));

        return Percentages.clamp(grown, Percentages.ZERO, Percentages.ONE_HUNDRED);
    }
}
// @GenAI-END
