// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.Instant;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public record ApiErrorResponse(int status,
                               String error,
                               String message,
                               List<String> details,
                               Instant timestamp) {

    public static ApiErrorResponse of(int status, String error, String message) {
        return new ApiErrorResponse(status, error, message, List.of(), Instant.now());
    }

    public static ApiErrorResponse of(int status, String error, String message, List<String> details) {
        return new ApiErrorResponse(status, error, message, details, Instant.now());
    }
}
// @GenAI-END
