// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api.dto;

import com.sportsgroup.jackpot.domain.Bet;
import com.sportsgroup.jackpot.domain.BetStatus;

import java.math.BigDecimal;
import java.time.Instant;

public record BetResponse(String betId,
                          String userId,
                          String jackpotId,
                          BigDecimal betAmount,
                          BetStatus status,
                          Instant createdAt,
                          Instant evaluatedAt) {

    public static BetResponse from(Bet bet) {
        return new BetResponse(
                bet.getId(),
                bet.getUserId(),
                bet.getJackpotId(),
                bet.getBetAmount(),
                bet.getStatus(),
                bet.getCreatedAt(),
                bet.getEvaluatedAt());
    }
}
// @GenAI-END
