// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api.dto;

import com.sportsgroup.jackpot.domain.JackpotContribution;

import java.math.BigDecimal;
import java.time.Instant;

public record ContributionResponse(String betId,
                                   String userId,
                                   String jackpotId,
                                   BigDecimal stakeAmount,
                                   BigDecimal contributionAmount,
                                   BigDecimal currentJackpotAmount,
                                   Instant createdAt) {

    public static ContributionResponse from(JackpotContribution contribution) {
        return new ContributionResponse(
                contribution.getBetId(),
                contribution.getUserId(),
                contribution.getJackpotId(),
                contribution.getStakeAmount(),
                contribution.getContributionAmount(),
                contribution.getCurrentJackpotAmount(),
                contribution.getCreatedAt());
    }
}
// @GenAI-END
