// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api.dto;

import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.RewardType;

import java.math.BigDecimal;

/**
 * A jackpot's pool state together with the contribution rate and win chance that apply
 * right now, which is what makes the variable strategies observable from outside.
 */
public record JackpotResponse(String jackpotId,
                              String name,
                              BigDecimal initialPoolAmount,
                              BigDecimal currentPoolAmount,
                              ContributionType contributionType,
                              BigDecimal currentContributionPercentage,
                              RewardType rewardType,
                              BigDecimal currentWinChancePercentage) {
}
// @GenAI-END
