// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api.dto;

import com.sportsgroup.jackpot.messaging.BetMessage;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * The bet to publish: bet id, user id, jackpot id and bet amount.
 */
public record PublishBetRequest(

        @NotBlank(message = "betId is required")
        @Size(max = 64, message = "betId must be at most 64 characters")
        String betId,

        @NotBlank(message = "userId is required")
        @Size(max = 64, message = "userId must be at most 64 characters")
        String userId,

        @NotBlank(message = "jackpotId is required")
        @Size(max = 64, message = "jackpotId must be at most 64 characters")
        String jackpotId,

        @NotNull(message = "betAmount is required")
        @DecimalMin(value = "0.01", message = "betAmount must be greater than zero")
        @Digits(integer = 17, fraction = 2, message = "betAmount must have at most 2 decimals")
        BigDecimal betAmount) {

    public BetMessage toMessage() {
        return new BetMessage(betId, userId, jackpotId, betAmount.setScale(2, RoundingMode.HALF_UP));
    }
}
// @GenAI-END
