// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api.dto;

import com.sportsgroup.jackpot.service.RewardEvaluation;

import java.math.BigDecimal;
import java.time.Instant;

public record RewardEvaluationResponse(String betId,
                                       String userId,
                                       String jackpotId,
                                       boolean won,
                                       BigDecimal rewardAmount,
                                       BigDecimal winChancePercentage,
                                       BigDecimal jackpotPoolAmount,
                                       boolean alreadyEvaluated,
                                       Instant evaluatedAt) {

    public static RewardEvaluationResponse from(RewardEvaluation evaluation) {
        return new RewardEvaluationResponse(
                evaluation.betId(),
                evaluation.userId(),
                evaluation.jackpotId(),
                evaluation.won(),
                evaluation.rewardAmount(),
                evaluation.winChancePercentage(),
                evaluation.jackpotPoolAmount(),
                evaluation.alreadyEvaluated(),
                evaluation.evaluatedAt());
    }
}
// @GenAI-END
