// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.repository;

import com.sportsgroup.jackpot.domain.Bet;
import org.springframework.data.jpa.repository.JpaRepository;

public interface BetRepository extends JpaRepository<Bet, String> {
}
// @GenAI-END
