// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.repository;

import com.sportsgroup.jackpot.domain.JackpotReward;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

public interface JackpotRewardRepository extends JpaRepository<JackpotReward, Long> {

    Optional<JackpotReward> findByBetId(String betId);
}
// @GenAI-END
