// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.repository;

import com.sportsgroup.jackpot.domain.JackpotContribution;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

public interface JackpotContributionRepository extends JpaRepository<JackpotContribution, Long> {

    Optional<JackpotContribution> findByBetId(String betId);

    boolean existsByBetId(String betId);

    /**
     * Ordered by insertion as the tie-breaker, because two contributions can share a
     * timestamp and the order they were applied in must still be reproducible.
     */
    List<JackpotContribution> findByJackpotIdOrderByCreatedAtAscIdAsc(String jackpotId);
}
// @GenAI-END
