// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.repository;

import com.sportsgroup.jackpot.domain.Jackpot;
import jakarta.persistence.LockModeType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Lock;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Optional;

public interface JackpotRepository extends JpaRepository<Jackpot, String> {

    /**
     * Loads a jackpot with a row-level write lock.
     *
     * <p>Contributing to a pool and paying a pool out are both read-modify-write cycles, so
     * concurrent bets on the same jackpot must be serialised or contributions would be lost.
     */
    @Lock(LockModeType.PESSIMISTIC_WRITE)
    @Query("select j from Jackpot j where j.id = :id")
    Optional<Jackpot> findByIdForUpdate(@Param("id") String id);
}
// @GenAI-END
