// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.support;

import com.sportsgroup.jackpot.service.reward.ChanceEvaluator;

import java.math.BigDecimal;

/**
 * A {@link ChanceEvaluator} whose outcome the test decides, so the reward flow can be
 * asserted without depending on a random draw.
 */
public class ControllableChanceEvaluator implements ChanceEvaluator {

    private Boolean forcedOutcome;
    private BigDecimal lastEvaluatedChance;

    public void alwaysWin() {
        this.forcedOutcome = Boolean.TRUE;
    }

    public void neverWin() {
        this.forcedOutcome = Boolean.FALSE;
    }

    public void reset() {
        this.forcedOutcome = null;
        this.lastEvaluatedChance = null;
    }

    /**
     * The chance the service asked about, which is how tests verify that the configured
     * strategy actually drove the evaluation.
     */
    public BigDecimal lastEvaluatedChance() {
        return lastEvaluatedChance;
    }

    @Override
    public boolean isWin(BigDecimal winChancePercentage) {
        this.lastEvaluatedChance = winChancePercentage;
        if (forcedOutcome == null) {
            throw new IllegalStateException(
                    "The test must call alwaysWin() or neverWin() before a reward is evaluated");
        }
        return forcedOutcome;
    }
}
// @GenAI-END
