// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.support;

import com.sportsgroup.jackpot.domain.ContributionConfig;
import com.sportsgroup.jackpot.domain.ContributionType;
import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.domain.RewardConfig;
import com.sportsgroup.jackpot.domain.RewardType;

import java.math.BigDecimal;

/**
 * Builders for jackpots in a known state, so calculator tests read as arrange/assert
 * rather than as constructor noise.
 */
public final class JackpotFixtures {

    private JackpotFixtures() {
    }

    public static Jackpot fixedContribution(String initialPool, String percentage) {
        return new Jackpot(
                "jackpot-fixed",
                "Fixed",
                new BigDecimal(initialPool),
                new ContributionConfig(ContributionType.FIXED, new BigDecimal(percentage), null, null, null),
                new RewardConfig(RewardType.FIXED, new BigDecimal("10"), null, null, null));
    }

    public static Jackpot variableContribution(String initialPool,
                                               String startPercentage,
                                               String minPercentage,
                                               String decayPerStep,
                                               String poolStepAmount) {
        return new Jackpot(
                "jackpot-variable",
                "Variable",
                new BigDecimal(initialPool),
                new ContributionConfig(
                        ContributionType.VARIABLE,
                        new BigDecimal(startPercentage),
                        new BigDecimal(minPercentage),
                        new BigDecimal(decayPerStep),
                        new BigDecimal(poolStepAmount)),
                new RewardConfig(RewardType.FIXED, new BigDecimal("10"), null, null, null));
    }

    public static Jackpot fixedReward(String initialPool, String chancePercentage) {
        return new Jackpot(
                "jackpot-fixed-reward",
                "Fixed reward",
                new BigDecimal(initialPool),
                new ContributionConfig(ContributionType.FIXED, new BigDecimal("5"), null, null, null),
                new RewardConfig(RewardType.FIXED, new BigDecimal(chancePercentage), null, null, null));
    }

    public static Jackpot variableReward(String initialPool,
                                         String startChance,
                                         String chanceGrowthPerStep,
                                         String poolStepAmount,
                                         String guaranteedPoolLimit) {
        return new Jackpot(
                "jackpot-variable-reward",
                "Variable reward",
                new BigDecimal(initialPool),
                new ContributionConfig(ContributionType.FIXED, new BigDecimal("5"), null, null, null),
                new RewardConfig(
                        RewardType.VARIABLE,
                        new BigDecimal(startChance),
                        new BigDecimal(chanceGrowthPerStep),
                        new BigDecimal(poolStepAmount),
                        guaranteedPoolLimit == null ? null : new BigDecimal(guaranteedPoolLimit)));
    }

    /**
     * Grows a jackpot's pool by the given amount using the aggregate's own behaviour.
     */
    public static Jackpot grownBy(Jackpot jackpot, String growth) {
        jackpot.contribute(new BigDecimal(growth));
        return jackpot;
    }
}
// @GenAI-END
