// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api;

import com.sportsgroup.jackpot.api.dto.ApiErrorResponse;
import com.sportsgroup.jackpot.exception.BetNotContributedException;
import com.sportsgroup.jackpot.exception.BetNotFoundException;
import com.sportsgroup.jackpot.exception.BetPublishFailedException;
import com.sportsgroup.jackpot.exception.DuplicateBetException;
import com.sportsgroup.jackpot.exception.JackpotNotFoundException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.util.List;

/**
 * Translates domain failures into HTTP responses so controllers stay free of error handling.
 */
@RestControllerAdvice
public class ApiExceptionHandler {

    private static final Logger log = LoggerFactory.getLogger(ApiExceptionHandler.class);

    @ExceptionHandler({BetNotFoundException.class, JackpotNotFoundException.class})
    public ResponseEntity<ApiErrorResponse> handleNotFound(RuntimeException e) {
        return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(ApiErrorResponse.of(HttpStatus.NOT_FOUND.value(), "Not Found", e.getMessage()));
    }

    @ExceptionHandler(DuplicateBetException.class)
    public ResponseEntity<ApiErrorResponse> handleDuplicateBet(DuplicateBetException e) {
        return ResponseEntity.status(HttpStatus.CONFLICT)
                .body(ApiErrorResponse.of(HttpStatus.CONFLICT.value(), "Conflict", e.getMessage()));
    }

    @ExceptionHandler(BetNotContributedException.class)
    public ResponseEntity<ApiErrorResponse> handleBetNotContributed(BetNotContributedException e) {
        return ResponseEntity.status(HttpStatus.UNPROCESSABLE_ENTITY)
                .body(ApiErrorResponse.of(
                        HttpStatus.UNPROCESSABLE_ENTITY.value(), "Unprocessable Entity", e.getMessage()));
    }

    @ExceptionHandler(BetPublishFailedException.class)
    public ResponseEntity<ApiErrorResponse> handlePublishFailure(BetPublishFailedException e) {
        log.error("Bet could not be published", e);
        return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE)
                .body(ApiErrorResponse.of(
                        HttpStatus.SERVICE_UNAVAILABLE.value(), "Service Unavailable", e.getMessage()));
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiErrorResponse> handleValidation(MethodArgumentNotValidException e) {
        List<String> details = e.getBindingResult().getFieldErrors().stream()
                .map(FieldError::getDefaultMessage)
                .sorted()
                .toList();
        return ResponseEntity.badRequest()
                .body(ApiErrorResponse.of(
                        HttpStatus.BAD_REQUEST.value(), "Bad Request", "The bet is not valid", details));
    }

    @ExceptionHandler(IllegalStateException.class)
    public ResponseEntity<ApiErrorResponse> handleMisconfiguration(IllegalStateException e) {
        log.error("Jackpot configuration problem", e);
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(ApiErrorResponse.of(
                        HttpStatus.INTERNAL_SERVER_ERROR.value(), "Internal Server Error", e.getMessage()));
    }
}
// @GenAI-END
