// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api;

import com.sportsgroup.jackpot.api.dto.BetResponse;
import com.sportsgroup.jackpot.api.dto.PublishBetRequest;
import com.sportsgroup.jackpot.api.dto.RewardEvaluationResponse;
import com.sportsgroup.jackpot.domain.Bet;
import com.sportsgroup.jackpot.service.BetService;
import com.sportsgroup.jackpot.service.RewardEvaluation;
import com.sportsgroup.jackpot.service.RewardService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/bets")
public class BetController {

    private final BetService betService;
    private final RewardService rewardService;

    public BetController(BetService betService, RewardService rewardService) {
        this.betService = betService;
        this.rewardService = rewardService;
    }

    /**
     * Use case 1: publish a bet to the {@code jackpot-bets} topic.
     *
     * <p>Returns 202 Accepted because contribution happens on the consumer side.
     */
    @PostMapping
    public ResponseEntity<BetResponse> publishBet(@Valid @RequestBody PublishBetRequest request) {
        Bet bet = betService.publishBet(request.toMessage());
        return ResponseEntity.status(HttpStatus.ACCEPTED).body(BetResponse.from(bet));
    }

    /**
     * Use case 4: evaluate whether this bet wins the jackpot reward.
     */
    @PostMapping("/{betId}/evaluate")
    public ResponseEntity<RewardEvaluationResponse> evaluateReward(@PathVariable String betId) {
        RewardEvaluation evaluation = rewardService.evaluate(betId);
        return ResponseEntity.ok(RewardEvaluationResponse.from(evaluation));
    }

    /**
     * Shows what the service did with a bet, which is how the outcome of the asynchronous
     * contribution is observed.
     */
    @GetMapping("/{betId}")
    public ResponseEntity<BetResponse> getBet(@PathVariable String betId) {
        return ResponseEntity.ok(BetResponse.from(betService.findBet(betId)));
    }
}
// @GenAI-END
