// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.api;

import com.sportsgroup.jackpot.api.dto.ContributionResponse;
import com.sportsgroup.jackpot.api.dto.JackpotResponse;
import com.sportsgroup.jackpot.service.JackpotQueryService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/v1/jackpots")
public class JackpotController {

    private final JackpotQueryService jackpotQueryService;

    public JackpotController(JackpotQueryService jackpotQueryService) {
        this.jackpotQueryService = jackpotQueryService;
    }

    @GetMapping
    public ResponseEntity<List<JackpotResponse>> listJackpots() {
        return ResponseEntity.ok(jackpotQueryService.findAll());
    }

    @GetMapping("/{jackpotId}")
    public ResponseEntity<JackpotResponse> getJackpot(@PathVariable String jackpotId) {
        return ResponseEntity.ok(jackpotQueryService.findById(jackpotId));
    }

    @GetMapping("/{jackpotId}/contributions")
    public ResponseEntity<List<ContributionResponse>> listContributions(@PathVariable String jackpotId) {
        List<ContributionResponse> contributions = jackpotQueryService.findContributions(jackpotId).stream()
                .map(ContributionResponse::from)
                .toList();
        return ResponseEntity.ok(contributions);
    }
}
// @GenAI-END
