// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.service.reward;

import com.sportsgroup.jackpot.domain.Jackpot;
import com.sportsgroup.jackpot.support.JackpotFixtures;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.assertj.core.api.Assertions.assertThat;

class RewardChanceCalculatorTest {

    @Nested
    @DisplayName("fixed chance")
    class Fixed {

        private final FixedRewardChanceCalculator calculator = new FixedRewardChanceCalculator();

        @Test
        @DisplayName("returns the configured chance")
        void returnsConfiguredChance() {
            assertThat(calculator.winChancePercentage(JackpotFixtures.fixedReward("10000.00", "10")))
                    .isEqualByComparingTo("10");
        }

        @Test
        @DisplayName("keeps the same chance however large the pool grows")
        void keepsSameChanceAsPoolGrows() {
            Jackpot jackpot = JackpotFixtures.grownBy(JackpotFixtures.fixedReward("10000.00", "10"), "900000.00");

            assertThat(calculator.winChancePercentage(jackpot)).isEqualByComparingTo("10");
        }
    }

    @Nested
    @DisplayName("variable chance")
    class Variable {

        private final VariableRewardChanceCalculator calculator = new VariableRewardChanceCalculator();

        /**
         * Starts at 1%, gains 5 percentage points per 10,000 of pool growth, guaranteed at 100,000.
         */
        private Jackpot jackpot() {
            return JackpotFixtures.variableReward("0.00", "1", "5", "10000.00", "100000.00");
        }

        @Test
        @DisplayName("starts at the configured chance while the pool has not grown")
        void startsAtConfiguredChance() {
            assertThat(calculator.winChancePercentage(jackpot())).isEqualByComparingTo("1");
        }

        @ParameterizedTest(name = "pool grown by {0} wins {1}% of the time")
        @CsvSource({
                "0.00,        1",
                "10000.00,    6",
                "25000.00, 13.5",
                "50000.00,   26"
        })
        @DisplayName("raises the chance as the pool grows")
        void raisesChanceAsPoolGrows(String growth, String expectedChance) {
            Jackpot jackpot = JackpotFixtures.grownBy(jackpot(), growth);

            assertThat(calculator.winChancePercentage(jackpot)).isEqualByComparingTo(expectedChance);
        }

        @Test
        @DisplayName("guarantees a win once the pool reaches the configured limit")
        void guaranteesWinAtPoolLimit() {
            Jackpot atLimit = JackpotFixtures.grownBy(jackpot(), "100000.00");
            Jackpot beyondLimit = JackpotFixtures.grownBy(jackpot(), "250000.00");

            assertThat(calculator.winChancePercentage(atLimit)).isEqualByComparingTo("100");
            assertThat(calculator.winChancePercentage(beyondLimit)).isEqualByComparingTo("100");
        }

        @Test
        @DisplayName("never exceeds 100% even without a configured pool limit")
        void neverExceedsOneHundredPercent() {
            Jackpot withoutLimit = JackpotFixtures.grownBy(
                    JackpotFixtures.variableReward("0.00", "1", "5", "10000.00", null), "900000.00");

            assertThat(calculator.winChancePercentage(withoutLimit)).isEqualByComparingTo("100");
        }
    }
}
// @GenAI-END
