// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.messaging;

import com.sportsgroup.jackpot.service.BetProcessingService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Consumes the {@code jackpot-bets} topic and feeds each bet into the contribution flow.
 *
 * <p>Active only when {@code jackpot.kafka.enabled=true}; otherwise
 * {@link MockBetPublisher} drives the same processing in-process.
 */
@Component
@ConditionalOnProperty(name = "jackpot.kafka.enabled", havingValue = "true")
public class BetKafkaListener {

    private static final Logger log = LoggerFactory.getLogger(BetKafkaListener.class);

    private final BetProcessingService betProcessingService;

    public BetKafkaListener(BetProcessingService betProcessingService) {
        this.betProcessingService = betProcessingService;
    }

    @KafkaListener(topics = "${jackpot.kafka.topic}", groupId = "${spring.kafka.consumer.group-id}")
    public void onBet(BetMessage betMessage) {
        log.info("Consumed bet {} from topic", betMessage.betId());
        betProcessingService.process(betMessage);
    }
}
// @GenAI-END
