// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.messaging;

import java.math.BigDecimal;

/**
 * The bet payload carried on the {@code jackpot-bets} topic, exactly the four fields the
 * requirements define for a bet.
 *
 * @param betId     unique identifier of the bet, also the Kafka message key
 * @param userId    the user who placed the bet
 * @param jackpotId the jackpot the bet should contribute to
 * @param betAmount the stake
 */
public record BetMessage(String betId, String userId, String jackpotId, BigDecimal betAmount) {
}
// @GenAI-END
