// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.messaging;

/**
 * Publishes a bet to the {@code jackpot-bets} topic.
 *
 * <p>The API depends on this abstraction rather than on {@code KafkaTemplate}, so the
 * service runs both against a real broker and against the mock publisher the assignment
 * allows, without the controller or service layer knowing the difference.
 */
public interface BetPublisher {

    void publish(BetMessage betMessage);
}
// @GenAI-END
