// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.messaging;

import com.sportsgroup.jackpot.config.JackpotProperties;
import com.sportsgroup.jackpot.exception.BetPublishFailedException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Component;

/**
 * Publishes bets to a real Kafka broker, keyed by bet id so that all messages for a bet
 * land on the same partition and are processed in order.
 *
 * <p>Active only when {@code jackpot.kafka.enabled=true}.
 */
@Component
@ConditionalOnProperty(name = "jackpot.kafka.enabled", havingValue = "true")
public class KafkaBetPublisher implements BetPublisher {

    private static final Logger log = LoggerFactory.getLogger(KafkaBetPublisher.class);

    private final KafkaTemplate<String, BetMessage> kafkaTemplate;
    private final String topic;

    public KafkaBetPublisher(KafkaTemplate<String, BetMessage> kafkaTemplate,
                             JackpotProperties properties) {
        this.kafkaTemplate = kafkaTemplate;
        this.topic = properties.getKafka().getTopic();
    }

    @Override
    public void publish(BetMessage betMessage) {
        try {
            kafkaTemplate.send(topic, betMessage.betId(), betMessage).get();
            log.info("Published bet {} to topic {}", betMessage.betId(), topic);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new BetPublishFailedException(betMessage.betId(), e);
        } catch (Exception e) {
            throw new BetPublishFailedException(betMessage.betId(), e);
        }
    }
}
// @GenAI-END
