// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.messaging;

import com.sportsgroup.jackpot.config.JackpotProperties;
import com.sportsgroup.jackpot.service.BetProcessingService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/**
 * Stands in for Kafka when no broker is available, which is the fallback the assignment
 * explicitly allows: the payload is logged and then handed to the very same
 * {@link BetProcessingService} that the real Kafka listener calls.
 *
 * <p>Delivery is in-process and synchronous. That keeps the service runnable and testable
 * with no infrastructure, and means a bet is contributed by the time the API responds. A
 * consumer failure is logged rather than propagated, mirroring Kafka, where a consumer
 * error never fails the producer's send.
 *
 * <p>Active by default, and replaced by {@link KafkaBetPublisher} when
 * {@code jackpot.kafka.enabled=true}.
 */
@Component
@ConditionalOnProperty(name = "jackpot.kafka.enabled", havingValue = "false", matchIfMissing = true)
public class MockBetPublisher implements BetPublisher {

    private static final Logger log = LoggerFactory.getLogger(MockBetPublisher.class);

    private final BetProcessingService betProcessingService;
    private final String topic;

    public MockBetPublisher(BetProcessingService betProcessingService,
                            JackpotProperties properties) {
        this.betProcessingService = betProcessingService;
        this.topic = properties.getKafka().getTopic();
    }

    @Override
    public void publish(BetMessage betMessage) {
        log.info("[MOCK KAFKA] topic={} key={} payload={}", topic, betMessage.betId(), betMessage);
        try {
            betProcessingService.process(betMessage);
        } catch (RuntimeException e) {
            log.error("[MOCK KAFKA] consumer failed for bet {}", betMessage.betId(), e);
        }
    }
}
// @GenAI-END
