// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class JackpotServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(JackpotServiceApplication.class, args);
    }
}
// @GenAI-END
