// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * A bet received by the service.
 *
 * <p>This table is not prescribed by the requirements; it exists so that the bet id can be
 * rejected as a duplicate at the API boundary, so the outcome of asynchronous processing is
 * observable, and so a bet can only be evaluated for a reward once.
 */
@Entity
@Table(name = "bet")
public class Bet {

    @Id
    @Column(name = "id", nullable = false, length = 64)
    private String id;

    @Column(name = "user_id", nullable = false, length = 64)
    private String userId;

    @Column(name = "jackpot_id", nullable = false, length = 64)
    private String jackpotId;

    @Column(name = "bet_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal betAmount;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 32)
    private BetStatus status;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /** Set the first time the bet is evaluated for a reward; keeps the roll one-shot. */
    @Column(name = "evaluated_at")
    private Instant evaluatedAt;

    protected Bet() {
        // for JPA
    }

    public Bet(String id,
               String userId,
               String jackpotId,
               BigDecimal betAmount,
               Instant createdAt) {
        this.id = id;
        this.userId = userId;
        this.jackpotId = jackpotId;
        this.betAmount = betAmount;
        this.status = BetStatus.PUBLISHED;
        this.createdAt = createdAt;
    }

    public void markContributed() {
        this.status = BetStatus.CONTRIBUTED;
    }

    public void markNoMatchingJackpot() {
        this.status = BetStatus.NO_MATCHING_JACKPOT;
    }

    public void markEvaluated(Instant evaluatedAt) {
        this.evaluatedAt = evaluatedAt;
    }

    public boolean isEvaluated() {
        return evaluatedAt != null;
    }

    public String getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public String getJackpotId() {
        return jackpotId;
    }

    public BigDecimal getBetAmount() {
        return betAmount;
    }

    public BetStatus getStatus() {
        return status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getEvaluatedAt() {
        return evaluatedAt;
    }
}
// @GenAI-END
