// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

/**
 * Lifecycle of a bet inside this service.
 */
public enum BetStatus {

    /** Accepted by the API and published to the topic, not yet consumed. */
    PUBLISHED,

    /** Consumed and contributed to its jackpot pool. */
    CONTRIBUTED,

    /** Consumed, but no jackpot matched the bet's jackpot id, so nothing was contributed. */
    NO_MATCHING_JACKPOT
}
// @GenAI-END
