// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;

import java.math.BigDecimal;

/**
 * Per-jackpot contribution settings. Which fields are meaningful depends on
 * {@link #getType()}; each calculator reads only the ones it needs.
 */
@Embeddable
public class ContributionConfig {

    @Enumerated(EnumType.STRING)
    @Column(name = "contribution_type", nullable = false, length = 32)
    private ContributionType type;

    /** FIXED: the contribution percentage. VARIABLE: the starting percentage. */
    @Column(name = "contribution_percentage", precision = 9, scale = 4)
    private BigDecimal percentage;

    /** VARIABLE: the floor the percentage decays towards. */
    @Column(name = "contribution_min_percentage", precision = 9, scale = 4)
    private BigDecimal minPercentage;

    /** VARIABLE: percentage points removed per {@link #getPoolStepAmount()} of pool growth. */
    @Column(name = "contribution_decay_percentage_per_step", precision = 9, scale = 4)
    private BigDecimal decayPercentagePerStep;

    /** VARIABLE: the amount of pool growth that constitutes one decay step. */
    @Column(name = "contribution_pool_step_amount", precision = 19, scale = 2)
    private BigDecimal poolStepAmount;

    protected ContributionConfig() {
        // for JPA
    }

    public ContributionConfig(ContributionType type,
                              BigDecimal percentage,
                              BigDecimal minPercentage,
                              BigDecimal decayPercentagePerStep,
                              BigDecimal poolStepAmount) {
        this.type = type;
        this.percentage = percentage;
        this.minPercentage = minPercentage;
        this.decayPercentagePerStep = decayPercentagePerStep;
        this.poolStepAmount = poolStepAmount;
    }

    public ContributionType getType() {
        return type;
    }

    public BigDecimal getPercentage() {
        return percentage;
    }

    public BigDecimal getMinPercentage() {
        return minPercentage;
    }

    public BigDecimal getDecayPercentagePerStep() {
        return decayPercentagePerStep;
    }

    public BigDecimal getPoolStepAmount() {
        return poolStepAmount;
    }
}
// @GenAI-END
