// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

/**
 * How a jackpot turns a stake into a pool contribution.
 *
 * <p>Adding a new strategy means adding a constant here and a matching
 * {@code ContributionCalculator} bean; nothing else needs to change.
 */
public enum ContributionType {

    /** A constant percentage of the stake. */
    FIXED,

    /** A percentage that starts high and decreases at a fixed rate as the pool grows. */
    VARIABLE
}
// @GenAI-END
