// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * The record of a jackpot payout, as defined by the requirements: bet, user, jackpot,
 * reward amount and creation time.
 *
 * <p>{@code bet_id} is unique so a single bet can never be paid out twice.
 */
@Entity
@Table(name = "jackpot_reward",
        uniqueConstraints = @UniqueConstraint(name = "uk_reward_bet_id", columnNames = "bet_id"))
public class JackpotReward {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "bet_id", nullable = false, length = 64)
    private String betId;

    @Column(name = "user_id", nullable = false, length = 64)
    private String userId;

    @Column(name = "jackpot_id", nullable = false, length = 64)
    private String jackpotId;

    @Column(name = "jackpot_reward_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal jackpotRewardAmount;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    protected JackpotReward() {
        // for JPA
    }

    public JackpotReward(String betId,
                         String userId,
                         String jackpotId,
                         BigDecimal jackpotRewardAmount,
                         Instant createdAt) {
        this.betId = betId;
        this.userId = userId;
        this.jackpotId = jackpotId;
        this.jackpotRewardAmount = jackpotRewardAmount;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public String getBetId() {
        return betId;
    }

    public String getUserId() {
        return userId;
    }

    public String getJackpotId() {
        return jackpotId;
    }

    public BigDecimal getJackpotRewardAmount() {
        return jackpotRewardAmount;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
// @GenAI-END
