// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * The record of a single bet's contribution to a jackpot pool, as defined by the
 * requirements: bet, user, jackpot, stake, contribution and the resulting pool amount.
 *
 * <p>{@code bet_id} is unique, which makes the consumer idempotent: a redelivered Kafka
 * message can never contribute twice.
 */
@Entity
@Table(name = "jackpot_contribution",
        uniqueConstraints = @UniqueConstraint(name = "uk_contribution_bet_id", columnNames = "bet_id"))
public class JackpotContribution {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "bet_id", nullable = false, length = 64)
    private String betId;

    @Column(name = "user_id", nullable = false, length = 64)
    private String userId;

    @Column(name = "jackpot_id", nullable = false, length = 64)
    private String jackpotId;

    @Column(name = "stake_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal stakeAmount;

    @Column(name = "contribution_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal contributionAmount;

    @Column(name = "current_jackpot_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal currentJackpotAmount;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    protected JackpotContribution() {
        // for JPA
    }

    public JackpotContribution(String betId,
                               String userId,
                               String jackpotId,
                               BigDecimal stakeAmount,
                               BigDecimal contributionAmount,
                               BigDecimal currentJackpotAmount,
                               Instant createdAt) {
        this.betId = betId;
        this.userId = userId;
        this.jackpotId = jackpotId;
        this.stakeAmount = stakeAmount;
        this.contributionAmount = contributionAmount;
        this.currentJackpotAmount = currentJackpotAmount;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public String getBetId() {
        return betId;
    }

    public String getUserId() {
        return userId;
    }

    public String getJackpotId() {
        return jackpotId;
    }

    public BigDecimal getStakeAmount() {
        return stakeAmount;
    }

    public BigDecimal getContributionAmount() {
        return contributionAmount;
    }

    public BigDecimal getCurrentJackpotAmount() {
        return currentJackpotAmount;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
// @GenAI-END
