// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.math.BigDecimal;

/**
 * A jackpot pool with its own initial value, contribution configuration and reward
 * configuration.
 *
 * <p>The pool amount is only ever changed through {@link #contribute(BigDecimal)} and
 * {@link #resetPool()} so that the invariants stay inside the aggregate.
 */
@Entity
@Table(name = "jackpot")
public class Jackpot {

    @Id
    @Column(name = "id", nullable = false, length = 64)
    private String id;

    @Column(name = "name", nullable = false, length = 128)
    private String name;

    @Column(name = "initial_pool_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal initialPoolAmount;

    @Column(name = "current_pool_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal currentPoolAmount;

    @Embedded
    private ContributionConfig contributionConfig;

    @Embedded
    private RewardConfig rewardConfig;

    protected Jackpot() {
        // for JPA
    }

    public Jackpot(String id,
                   String name,
                   BigDecimal initialPoolAmount,
                   ContributionConfig contributionConfig,
                   RewardConfig rewardConfig) {
        this.id = id;
        this.name = name;
        this.initialPoolAmount = initialPoolAmount;
        this.currentPoolAmount = initialPoolAmount;
        this.contributionConfig = contributionConfig;
        this.rewardConfig = rewardConfig;
    }

    /**
     * Adds a contribution to the pool and returns the new pool amount.
     */
    public BigDecimal contribute(BigDecimal contributionAmount) {
        this.currentPoolAmount = this.currentPoolAmount.add(contributionAmount);
        return this.currentPoolAmount;
    }

    /**
     * How much the pool has grown beyond its initial value. Never negative, which keeps
     * the variable calculators monotonic even right after a reset.
     */
    public BigDecimal poolGrowth() {
        return currentPoolAmount.subtract(initialPoolAmount).max(BigDecimal.ZERO);
    }

    /**
     * Called after the pool has been paid out as a reward.
     */
    public void resetPool() {
        this.currentPoolAmount = this.initialPoolAmount;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public BigDecimal getInitialPoolAmount() {
        return initialPoolAmount;
    }

    public BigDecimal getCurrentPoolAmount() {
        return currentPoolAmount;
    }

    public ContributionConfig getContributionConfig() {
        return contributionConfig;
    }

    public RewardConfig getRewardConfig() {
        return rewardConfig;
    }
}
// @GenAI-END
