// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

/**
 * How a jackpot decides the chance that a bet wins the pool.
 *
 * <p>Adding a new strategy means adding a constant here and a matching
 * {@code RewardChanceCalculator} bean; nothing else needs to change.
 */
public enum RewardType {

    /** A constant win chance. */
    FIXED,

    /** A chance that starts low and grows as the pool grows, reaching 100% at a pool limit. */
    VARIABLE
}
// @GenAI-END
