// @GenAI-START - Generated by Cursor on 2026-09-13
package com.sportsgroup.jackpot.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;

import java.math.BigDecimal;

/**
 * Per-jackpot reward settings. Which fields are meaningful depends on
 * {@link #getType()}; each calculator reads only the ones it needs.
 */
@Embeddable
public class RewardConfig {

    @Enumerated(EnumType.STRING)
    @Column(name = "reward_type", nullable = false, length = 32)
    private RewardType type;

    /** FIXED: the win chance. VARIABLE: the starting chance. */
    @Column(name = "reward_chance_percentage", precision = 9, scale = 4)
    private BigDecimal chancePercentage;

    /** VARIABLE: percentage points added per {@link #getPoolStepAmount()} of pool growth. */
    @Column(name = "reward_chance_growth_percentage_per_step", precision = 9, scale = 4)
    private BigDecimal chanceGrowthPercentagePerStep;

    /** VARIABLE: the amount of pool growth that constitutes one growth step. */
    @Column(name = "reward_pool_step_amount", precision = 19, scale = 2)
    private BigDecimal poolStepAmount;

    /** VARIABLE: once the pool reaches this amount the next evaluated bet always wins. */
    @Column(name = "reward_guaranteed_pool_limit", precision = 19, scale = 2)
    private BigDecimal guaranteedPoolLimit;

    protected RewardConfig() {
        // for JPA
    }

    public RewardConfig(RewardType type,
                        BigDecimal chancePercentage,
                        BigDecimal chanceGrowthPercentagePerStep,
                        BigDecimal poolStepAmount,
                        BigDecimal guaranteedPoolLimit) {
        this.type = type;
        this.chancePercentage = chancePercentage;
        this.chanceGrowthPercentagePerStep = chanceGrowthPercentagePerStep;
        this.poolStepAmount = poolStepAmount;
        this.guaranteedPoolLimit = guaranteedPoolLimit;
    }

    public RewardType getType() {
        return type;
    }

    public BigDecimal getChancePercentage() {
        return chancePercentage;
    }

    public BigDecimal getChanceGrowthPercentagePerStep() {
        return chanceGrowthPercentagePerStep;
    }

    public BigDecimal getPoolStepAmount() {
        return poolStepAmount;
    }

    public BigDecimal getGuaranteedPoolLimit() {
        return guaranteedPoolLimit;
    }
}
// @GenAI-END
